site_name: Teaching Assistant 

theme:
  name: null
  custom_dir: 'cinder'
repo_url: https://lucasmoschen.github.io
repo_name: Página Inicial

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML