site_name: Teaching Assistance
nav: 
  - Home: index.md
  - Álgebra Linear: alglin/info.md
  - Análise Numérica: analisenum/info.md
  - Curvas: curvas/info.md
  - EDO: edo/info.md
  - EDP: edp/info.md
  - Estatística: 
    - Inferência Estatística: infestatistica/info.md
    - Estatística Bayesiana: bayesian/info.md

theme:
  name: null
  custom_dir: 'cinder'
repo_url: https://lucasmoschen.github.io
repo_name: Página Inicial

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - pymdownx.extra