site_name: Teaching Assistant 
nav: 
  - Home: index.md
  - Inferência à Estatística: 
    - Notebook 1: index.md
    - Notebook 2: index.md
  - Equações Diferenciais: about.md
  - Álgebra Linear: about.md
theme: mkdocs
