site_name: Teaching Assistant 
nav: 
  - Home: index.md
  - Curvas e Superfícies: curvas/info.md
  - Estatística: infestatistica/info.md
  - EDO: edo/info.md
  - Álgebra Linear: alglin/info.md

theme:
  name: null
  custom_dir: 'cinder'
repo_url: https://lucasmoschen.github.io
repo_name: Página Inicial

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
    - pymdownx.extra
