site_name: Teaching Assistant 
nav: 
  - Home: index.md
  - Inferência à Estatística: 
    - Informações Gerais: infestatistica/info.md
    - Notebook 2: about.md
  - Equações Diferenciais: infestatistica/info.md
  - Álgebra Linear: infestatistica/info.md
theme: mkdocs
